[project]
name = "flowbit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "unstructured[json]>=0.17.2",
]

[tool.uv.workspace]
members = ["app"]
